"""Add User

Revision ID: 4f704a7b5595
Revises: 
Create Date: 2020-10-04 18:12:53.132174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f704a7b5595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_firstname', sa.String(length=250), nullable=True),
    sa.Column('user_lastname', sa.String(length=250), nullable=True),
    sa.Column('user_email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
