"""Update

Revision ID: 50f4c172c859
Revises: 97f2330865a3
Create Date: 2020-10-08 19:15:20.211588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50f4c172c859'
down_revision = '97f2330865a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clause', 'clause_full_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clause', sa.Column('clause_full_text', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
